### ISSUE TITLE
homepage nav on mobile & desktop (including SEARCH)

### ISSUE THREAD

**Issue by chelseafischerlodike** [chelseafischerlodike/CKMK-Digital-Bella#73]
ON MOBILE: Adjust line height and or height of the sub menu under the product category

**Comment by DevStL** [comment]
more specifics on the change please

**Comment by peak9ine** [comment]
@DevStL and Nick...
I'll be posting new nav comps for desktop and mobile

**Comment by peak9ine** [comment]
Jay and Nick,

I've dropped to comps for this issue here: https://projects.invisionapp.com/d/main#/projects/prototypes/7862628

In summary (Nick and discussed) We'll be moving the search pink entry bar to the main nav. Once the nav is compressed below 960 the nav turns to mobile. So we'll have room to center the nav items and reduce padding accommodating for an always visible search bar until that mobile size kicks in. 

For mobile, there is a specific comp posted for this. For UX best practice I strongly recommend that the search be included in the main menu drop down. To make the user bounce between 2 navigation systems isn't the best option considering how small this site is. We'll combine this. And to make the sub menu work under products with minimal design impact we move the menu system to be left justified so we can indent a product category list underneath which will surely grow. 

Let me know if we need to review live.

**Comment by peak9ine** [comment]
@chelseafischerlodike @DevStL @murphyni Let's move this into code production for demo
